server:
  port: 7010

eureka:
  instance:
    hostname: eurekaServer7010

  client:
    # 是否将自己注册到Eureka-Server中，默认的为true
    register-with-eureka: false
    # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    fetch-registry: false